
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book_catalog
  labels:
    app: book_catalog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book_catalog
  template:
    metadata:
      labels:
        app: book_catalog
    spec:
      containers:
      - name: book_catalog
        image: book_catalog:latest
        ports:
        - containerPort: 3010
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          value: "postgresql://postgresql://sit722_kush_z2sq_user:JxC5xvGeM5gYT592LgylJTHTTjJFn28S@dpg-cr3dpmqj1k6c73dkpdqg-a.oregon-postgres.render.com/sit722_kush_z2sq"
        imagePullPolicy: IfNotPresent
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book_catalog
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 3010 
  type: ClusterIP
